sudo: false
language: ruby
cache: bundler
rvm:
- 2.2.4
addons:
  postgresql: "9.6"
  apt:
    packages:
    - postgresql-9.6-postgis-2.3
services:
  - postgresql
before_script:
- psql -U postgres -c "create extension postgis"
- psql -c 'create database parkez_test;' -U postgres
- bundle exec rake db:create db:migrate
bundler_args: "--without development"
script: bundle exec rspec --options .rspec
notifications:
  email: false
  slack:
    secure: Vw68NRRH1IEWRzPrzGzFKgK/jlcEmanCEgys23beJePP0+0jqBviePQbClebL0/WTxJDfvCWSCBa/inyDI0LDdNcxGCvUWiYM1RDP6sFg8FU7qcldSUiCpywTroX1KJmcFFs+fFvmK+dDlLUs6u/gY8bP3s9gEFyalxYZv8RnAuf9goYVcRBIJyXwOTCw8huclCpqO+Qi3/y9gqlNmsfZyLm9cfNhCyj49397LC6WyB15hO89jNmwsTXW/162FmeljezqCPMWtRt6NbQi+sWwLwDMZDRbK0G3KhUGiFX6gFtLl8529Sj6dvbut8QcoyBPqONai2Uwz+2DUahuIad/PV6CEfXLgK+qPhVEVJikJDeCKeMNB0udZQNpyG0tf9DcAKgC6u62wtLl2YKoE6LyYKeFphRXcQM22S+2KRqjQxux3QRwZ+xwzD+DWrvP/pSq362S/IAAcvuZbPqW/BlepLcqotqm1fTHoM6UkPhT07htFOiada+RJYO9akAiLqwc+Kao/+3cu+j78mR0dA/r4C7Xl6oNj0B7WMflc5IrmbMje4A6mwgz/KxPcq/oNztSaFOMxffBnf6PVPsf+CpQkAX2CQLc5NF8nnHRVosZerxVTLB2t0NxBcc4T3XDoq/QClDcIUtWJFIwhhT4hH+3tFakHWb0OoZSf5vdj9VLZw=
