version: '2'
services:
  db:
    image: mdillon/postgis:9.5
    ports:
      - "0.0.0.0:5432:5432"
  web:
    build: .
    ports:
      - "0.0.0.0:3000:3000"
    depends_on:
      - db
    environment:
      - POSTGRES_DB=parkez
    volumes:
      - .:/app
