version: '2'
services:
  db:
    image: mdillon/postgis:9.5
    ports:
      - "0.0.0.0:5432:5432"
  web:
    command: bundle install
    build: .
    ports:
      - "0.0.0.0:5000:5000"
    depends_on:
      - db
    environment:
      - POSTGRES_DB=parkez
      - DB_HOST=db
    volumes:
      - .:/app
