
pg_local: &pg_local
  adapter: postgresql
  username: <%= ENV['TRAVIS'] ? 'travis' : 'postgresql' %>
  host:     localhost

pg: &pg
  adapter: postgresql
  encoding: unicode

defaults: &defaults
  pool: 10
  timeout: 5000
  encoding: utf8

development:
  <<: *defaults
  <<: *pg_local
  database: parkez

test: &test
  <<: *defaults
  <<: *pg_local
  database: <%= ENV['TRAVIS'] ? 'myapp_test' : 'parkez-test' %>

production:
  <<: *defaults
  <<: *pg
  database: <%= ENV["DATABASE"] %>
  username: <%= ENV["DATABASE_USER"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  host: <%= ENV["DATABASE_HOST"] %>
