# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5766fe8bbf3a93bb4251c0b3121d217c6763470d113221c508f39236ede1567219655ec0429d841e91e01988e520b84b04ec7055ade65be8cdb69d815d8fac3b

test:
  secret_key_base: bec92511fd5d8dcfbfa27e4791c72bb327f5d171c6b0a470f82a89fcde43254a2e78da1d9ac4b8715b0c41c8c3a8512da7e07fee4e6c37306dd60d6b90657314

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
